openapi: 3.0.0
info:
  description: "API system"
  version: "1.0.10"
  title: "API messanger"

tags:
- name: "init dataBase"
  description: "Route only for admin"
- name: "Test"
  description: "Test Echo"
- name: "client"
  description: "Access to Client"

paths:
  /create_db:
    post:
      tags:
        - "init dataBase"
      summary: "Create all Tables in dataBase"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CreateDb"
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/InternalError'
  /echo/{message}:
    post:
      tags:
        - "Test"
      summary: "Test handler"
      parameters:
        - message: message for echo
          name: message
          required: true
          schema:
            type: string
            minimum: 1
          description: Message for echo
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Echo"
  /client/{id}:
    get:
      tags:
      - "client"
      summary: "get client by id"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The client ID
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Client"
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/InternalError'
    delete:
      tags:
      - "client"
      summary: "delete client by id"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The client ID
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Client"
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/InternalError'
  /client:
    get:
      tags:
      - "client"
      summary: "get all client"
      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Client"
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/InternalError'
    post:
      tags:
      - "client"
      summary: "Create a client"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Client"

      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Client"
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/InternalError'
    put:
      tags:
      - "client"
      summary: "Update a client"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Client"

      responses:
        "200":
          description: "successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Client"
        "403":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/InternalError'


components:
  responses:
    NotFound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorEntity'
    InternalError:
      description: Internal error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorEntity'
    Unauthorized:
      description: Forbidden operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorEntity'
  schemas:
    ErrorEntity:
      type: "object"
      properties:
        error:
          type: string
    CreateDb:
      type: "object"
      properties:
        ok:
          type: string
    Echo:
      type: "object"
      properties:
        ok:
          type: bool
        message:
          type: string
    Client:
      type: "object"
      properties:
        id:
          type: integer
        createdAt:
          type: string
        name:
          type: string
        email:
          type: string
        cpf:
          type: string
        city:
          type: string
        state:
          type: string